id = "koala-theme"
name = "Kolaa Theme"
version = "0.1.0"
schema_version = 1
authors = "nerdalytics"
description = "A color scheme that is easy on the eyes by day and night."
repository = "https://github.com/nerdalytics/koala-theme-zed"
